import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class HeroesService {
  private heroes: Heroe [] = [
    {
      nombre: 'Aquaman',
      bio: 'Aquaman es hijo del farero Thomas Curry y la reina de Atlántida, Atlanna. Al menos, así estaba establecido en la historias de la edad de plata. A partir de la serie Crisis en Tierras Infinitas, su origen cambió a completamente atlante. En esta nueva realidad, su padre es Atlan, un misterioso mago de Atlántida. Sin embargo, ante la superstición de portar la maldición de Kordax, el bebé es abandonado en Mercy Reef. Allí es criado por el humano Thomas Curry, que le da el nombre de Arthur. Por lo tanto, durante su infancia, vive sin conocer su linaje real. En su regreso a la Atlántida, encuentra su principal valedor en la figura de Nuidis Vulko, un científico atlante e importante figura política en el reino, llegando a ser consejero del propio Aquaman. Otros personajes cercanos al Rey de los Siete Mares son Mera, su esposa perteneciente a la dimensión Aqua y Garth, un joven atlante que se convertirá en Aqualad, el pupilo de Aquaman. Posteriormente, éste será conocido en los cómics como Tempest. Entre sus enemigos más destacados están el Amo del Océano y Black Manta. Ambos se postulan como los principales rivales del Rey de los Siete Mares. Orm Marius, conocido  bajo el sobrenombre de Amo del Océano, es el medio hermano de Aquaman. En los eventos pre-crisis, Orm es el hermano completamente humano, hijo de Tom Curry y su segunda esposa. Crece a la sombra de su hermano y resentido con él por no tener sus mismos poderes. Años más tarde reaparece como Amo del Océano con un traje que le permite respirar bajo el agua y lucha contra Aquaman por el trono. Tras los eventos de Crisis en Tierras Infinitas, la historia de este personaje se reescribe. Sigue siendo hermano de Aquaman, pero esta vez es hijo del mago atlante Atlan. Como ya sucedía en las historias anteriores, Orm desea el trono de su hermano.',
      img: 'assets/img/aquamanperfil1.png',
      aparicion: ' 01 Noviembre de 1941',
      casa: 'DC',
      poder: 'El tridente que le otorga Poseidón es indestructible y un arma cuerpo a cuerpo muy poderosa. Además, cuenta con el poder de manipular el agua, disparar rayos de energía potentes y actuar como un foco para ampliar el poder mágico de los demás. Otra de las armas que posee es la mano izquierda hecha de agua dada por la Dama del Lago. Esta le otorga habilidades como la capacidad de deshidratar a quien toque, la capacidad de disparar agua de sus mano, así como escaldar o congelar a sus oponentes. Además, también le permite comunicarse con la Dama del Lago.',
      perfil: 'Aquaman es el gobernante de Atlántida. Recibe el nombre de Arthur Curry entre humanos, mientras que para su reino soberano es conocido como Orin. También es considerado uno de los miembros fundadores de la Liga de la Justicia.',
    },
    {
      nombre: 'Batman',
      bio: 'Bruce Wayne nació hijo del empresario multimillonario Thomas, inspirado por su propio padre para luchar contra el crimen, y Martha Wayne. Creciendo en la Mansión Wayne, Bruce cayó a la edad de ocho años a una caverna situada bajo la mansión, y llena de murciélagos, lo que resultó una experiencia traumática, a pesar del pronto rescate de su padre. Cuando solo tenía ocho años, Bruce contempló como el criminal Joe Chill asesinaba a sus padres, y escapaba, aunque sería arrestado más tarde. La médico y agente social, Leslie Thompkins se encargó de consolar al joven niño, que fue criado por el leal mayordomo de la familia, y su tutor legal, Alfred Pennyworth en la Mansión Wayne. Bruce tuvo escasos amigos durante su infancia, y uno de ellos se convertiría en su más mortal enemigo. La muerte de sus padres, inspiró a Bruce, que juró dedicar su vida para eliminar el mal que plagaba la ciudad de Gotham. Pasó su juventud viajando por el mundo, y entrenándose para obtener la perfección intelectual y física. Aprendió varias habilidades para la lucha contra el crimen, incluyendo química, criminología, antropología forense, artes marciales, gimnasia, y el arte del disfraz. A la edad de catorce años, comenzó sus viajes, asistiendo a clases en Cambridge, Sorbonne, y otras universidades europeas. Sin embargo, no permaneció demasiado tiempo en el mismo sitio. Durante su estancia en el extranjero, Bruce aprendió a dominar hasta ciento veintisiete estilos de combate, desde Aikido hasta el Yaw-Yan. Un francés llamado Henri Ducard le convirtió en su aprendiz en el arte de la persecución y localización de personas. Varios maestros Ninja le entrenaron en el arte del sigilo, y los caminos del guerrero de la sombra. Los Bushmen africanos le inculcaron técnicas de caza, mientras que monjes de Nepal le revelaron artes curativas. Llegó a aprender ventrilocuismo de algunos expertos del mencionado arte. Su conocimiento de tantas disciplinas le convirtió en un oponente poco convencional e impredecible. A la edad de 20 años, intentó ingresar en el FBI, pero se dio cuenta de que sería imposible luchar contra el crimen desde el sistema legal.',
      img: 'assets/img/batmanperfil2.jpg',
      aparicion: '27 de Mayo 1939',
      casa: 'DC',
      poder: 'Batman no posee ningún tipo de poder sobrehumano. Debido a un intenso entrenamiento, una dieta especializada y tratamientos especializados, Batman representa el perfecto estado físico de un ser humano. Su fuerza, velocidad, reflejos, agilidad, estamínea y coordinación, son prácticamente perfectos. Además ha aprendido hasta 127 estilos de combate, entre los que figuran Karate, Judo, Jujitsu, Aikido, Savate, King Fu, Ninjitsu, Muay Thai, Kobudo, Yaw-Yan, y Tae Kwon Do entre otros muchos. Controla también el arte de usa armas tales como esgrima, lanzamiento de armas blancas, uso del arco, y otros varios. Su mente también esta entrenada para alcanzar su más alto potencial. Habla a la perfección Español, Francés, Latín, Alemán, Japonés, Ruso, Contonéese, y Mandarin entre otros. Es un experto detective, estratega y posee una memoria fotográfica.Posee las más modernas armas para combatir, así como medios de transporte de avanzada tecnología que le permiten transportarse por tierra, aire y mar.',
      perfil: 'Batman es la identidad secreta de Bruce Wayne, un empresario multimillonario que presenció un asesinato cuando era niño, lo marcó profundamente y lo llevó a entrenarse en la perfección para ponerse un disfraz de murciélago con el fin de combatir el crimen.'
    },
    {
      nombre: 'Daredevil',
      bio: 'Matthew Murdock nació en 1979. Pierde la vista a temprana edad como resultado de un trágico accidente con productos químicos altamente venenosos. Hijo de Jonathan "Jack Batallador" Murdock, un boxeador venido a menos que, desde la presunta muerte de su esposa, había dejado el boxeo y bebía más de la cuenta. Aun así siempre obligó a Matt a estudiar antes que perder el tiempo en jugar. Por este motivo, algunos de los niños del barrio, le apodaron "Daredevil"(temerario, en inglés) en burla por no jugar nunca con ellos y pensando que era un cobarde empollón. Para poder financiar la educación de su hijo, Jonathan, ya en decadencia como boxeador, hizo un trato con el promotor de combates Roscoe Sweeney, apodado el Arreglador. Bajo la dirección de Sweeney logró relanzar su carrera, sin saber que todas sus peleas habían sido amañadas por su apoderado. Finalmente el Arreglador exigió a Murdock que perdiera un combate. Siendo un hombre honrado y no queriéndose humillar ante su hijo, que estaba presenciando la pelea, el veterano boxeador ganó el combate. En venganza, Sweeney mandó a sus matones, liderados por el llamado Slade para acabar con él. Matt, aunque hundido moralmente, consiguió terminar sus estudios y abrió su propio despacho de abogacía junto a Nelson. Matt quería llevar a los asesinos de su padre ante los tribunales, pero no tenía medios para acusarlos legalmente, así que terminó confeccionándose un disfraz y adoptando el nombre de "Daredevil". Así se enfrentó a Sweeney y Slade. Slade acabó confesando ante la policía y Sweeney murió de un infarto de miocardio a causa de la persecución. Matt continuó su lucha contra los criminales enfrentándose a muchos, como el Zancudo o el Gladiador, pero su principal adversario siempre ha sido el Kingpin. Éste contrató a Elektra, que se convirtió en su asesina principal, ello la llevó a enfrentarse contra Daredevil. Sin embargo, Bullseye, que aspiraba al puesto de Elektra, consiguió derrotarla hiriéndola mortalmente. Elektra murió en manos de Matt, al que amaba. Por ello la lucha de Daredevil contra Kingpin se recrudeció. Finalmente Kingpin decidió destrozar a su enemigo y le anuló la licencia como abogado y dinamitó su casa. Tras recuperarse se trasladó a la Cocina del Infierno, el barrio donde nació, y abrió un despacho de abogados para minusválidos y personas que no pudieran permitirse uno, económicamente hablando, aunque no pudiera representarlos jurídicamente debido a la pérdida de su licencia. Matt reencontró a Karen Page, quien conocía su doble identidad y ambos vivieron juntos trabajando en la asesoría. Kingpin, ante la reaparición de su antiguo enemigo, decidió destrozar su corazón, para ello contrató a Maria Tifoidea, quien consiguió enamorar a Matt. Justo en ese momento reunió a un grupo de delincuentes y consiguió apalizar a ',
      img: 'assets/img/Daredevilperfil1.png',
      aparicion: '01 Abril 1964',
      casa: 'Marvel',
      poder: 'A pesar de ser ciego, los sentidos de tacto, olfato, oído y gusto de Michael Murdock poseen niveles superhumanos. Su sentido del tacto esta tan desarrollado que le permite detectar detalles tan pequeños como la tinta en una pagina impresa. Su piel es igualmente sensible, lo que le permite notar cambios de temperatura y presión en sus alrededores. Su sentido del olfato es tan desarrollado que le permite diferenciar a dos hermanos gemelos, detectar olores de una concentración atmosférica, o identificar a cualquiera que haya estado con él durante un mínimo de cinco minutos. Su sentido del oído le permite detectar cambios de presión acústica, o escuchar el latido de una persona a considerable distancia y a una persona conversando con susurros al otro lado de una pared. Mediante práctica, Michael ha logrado desarrollar la capacidad de concentrarse en sonidos concretos eliminando otros, y discernir la sinceridad al escuchar el ritmo de los latidos del corazón. Su sentido del gusto le permite detectar todo los componentes de cualquier comida que consuma. Añadido a esto, posee un sentido del radar que le permite sentir la proximidad de objetos y personas. Dicho radar funciona através de energía procedente del espectro electromagnético, que su mente genera. Es además un atleta de nivel olímpico, con una agilidad, y velocidad excepcional, y ha recibido entrenamiento Ninja parcial, lo que le convierte en un luchador formidable.',
      perfil: 'Cegado como un niño en un accidente que dejó a sus otros sentidos mejorados a niveles extraordinarios, Matt Murdock lucha implacablemente por la ley y por la justicia, tanto como abogado defensor y como el duro luchador contra el crimen.'
    },
    {
      nombre: 'Hulk',
      bio: 'El hijo de un padre abusivo, Bruce Banner creció tímido e introvertido, pero un genio científico. De joven, gracias a su destacado trabajo en el campo de la física nuclear, atrajo la atención del Ejército de los Estados Unidos que querían adaptar sus teorías para el armamento. Banner se resistió a esas nociones, pero los intentos fallidos de aterrizar en un trabajo estable lo convencieron de aceptar una posición en una instalación federal de investigación nuclear en una base de misiles en el desierto de Nuevo México. En la base, Banner se hizo amigo de Betty Ross, hija del general Thaddeus “Thunderbolt” Ross, un hombre que tomó un instante de disgusto por el diminuto y pasivo científico. Mientras estaba en la base, Banner comenzó a desarrollar y construir una bomba que utilizaba una alta concentración de radiación gamma, un proyecto de gran interés para un agente extranjero encubierto estacionado allí. Cuando un adolescente llamado Rick Jones entró en el campo de prueba justo cuando Banner comenzó la cuenta regresiva para la detonación de la prueba de la bomba gamma, el científico se apresuró a ir al área para advertir a Jones, pero el agente extranjero continuó la prueba a propósito. La bomba explotó, bañando a Bruce Banner en su radiación. Increíblemente sobrevivió a la detonación, pero más tarde en la noche se transformó en una monstruosidad grande y gris parecida a un hombre, apodada “hulk” por uno de los soldados de la base.',
      img: 'assets/img/hulkperfil.jpg',
      aparicion: '01 Mayo 1962',
      casa: 'Marvel',
      poder: 'La fuerza de Hulk permanece en el nivel superior de todos los superhéroes en la Tierra y aumenta exponencialmente a medida que su ira crece. Esta fuerza no solo le otorga destreza en la parte superior del cuerpo, sino también la capacidad de saltar grandes distancias y aterrizar sin dañarse a sí mismo. La piel de Hulk es casi impenetrable y su capacidad pulmonar permite largos períodos de inmersión en agua, exposición a muchas formas de gases e incluso a la supervivencia temporal en el vacío sin aire en el espacio exterior.',
      perfil: 'Bruce Banner creció introvertido, pero un genio científico, gracias a su trabajo en el campo de la física nuclear, atrajo la atención del Ejército de USA. accidentalmente fue expuesto a una bomba de rayos gamma, convirtiéndose en un monstruo..'
    },
    {
      nombre: 'Linterna Verde',
      bio: 'La historia de Alan Scott como Linterna Verde tendría como su comienzo miles de años atrás cuando un meteorito rodeado de una místeriosa "llama verde" cayó en la antiguaChina. Una voz surgiría de la llama profetizando que actuaría tres veces: una para traer muerte (un fabricante de lámparas llamado Luke Fairclough elaboraría un candil(lámpara de aceite) a partir del metal verde del meteorito; como castigo por lo que pensaban sería un sacrilegio, la población local lo asesinaría, sólo para ser destruidos por un repentino estallido de la llama verde), otra para traer vida (en los tiempos modernos, la lámpara caería en manos de un paciente ingresado en una institución mental que la modificaría pasando a parecer una Lámpara de queroseno; la llama verde le devolvió la cordura, dándole con ello una nueva vida), y la última para traer poder. En 1940, la linterna llegaría a manos de Alan Scott, un joven ingeniero. Tras ser el único superviviente del colapso de un puente de ferrocarril y hallándose al borde de la muerte, la llama enseñaría a Scott cómo fabricar un anillo a partir de su metal, para darle increíbles poderes como el superhéroe Linterna Verde. Tras su primera aventura en la que se hizo pasar por un espíritu, adoptaría un llamativo y colorido traje con la intención de que a los criminales se les grabara su imagen en la memoria.',
      img: 'assets/img/linternaperfil.png',
      aparicion: '01 Junio 1940',
      casa: 'DC',
      poder: 'Cada Linterna Verde posee un anillo de poder y una batería (en forma de linterna) que garantiza a su portador la "posibilidad" de manifestar una gran variedad de poderes. Algo común entre todos son el poder de volar y el hecho de que todos los efectos de poder se manifiesten acompañados de una luz verde. El anillo está considerado dentro del Universo DC como una de las armas más poderosas jamás creadas y como algo muy peligroso en las manos equivocadas.',
      perfil: 'Hal Jordan es el primer humano en ser parte de la Corporación de Green Lanterns. Este es también el Lantern más poderoso de todos los tiempos y el más valeroso. Hal también ha tenido sus caidas pero aún así ha podido volver a ser un gran héroe'
    },
    {
      nombre: 'Spiderman',
      bio: 'El estudiante de secundaria y niño prodigio Peter Parker se sumergió en su pasión por la ciencia para evitar las burlas y amenazas de sus compañeros de clase y tropezó con un mundo más allá de lo que imaginaba. Mientras visitaba una exhibición pública de nuevos avances en la manipulación de la radiación y la genética, Parker sintió la mordedura de una araña doméstica común expuesta a un rayo de partículas y se sintió inmediatamente enfermo por ello, sin darse cuenta de cuánto cambiaría su vida en las próximas horas. En el camino a casa, el adolescente inconscientemente evitó un automóvil descarriado dando un salto increíble a la pared de un edificio cercano, encontrándose milagrosamente capaz de adherirse a él con sus manos y pies. Dándose cuenta rápidamente de que de alguna manera había adquirido las habilidades de una araña, comenzó a probar sus poderes recién descubiertos de los que se maravilló. Parker probó sus habilidades arácnidas en el ring de una competencia de lucha local y usando una máscara para ocultar su identidad, superó fácilmente al campeón reinante.',
      img: 'assets/img/spidermanperfil2.png',
      aparicion: '10 Agosto 1962',
      casa: 'Marvel',
      poder: 'Dispone de poderes especiales para enfrentar y derrotar a sus enemigos: fuerza, rapidez, reflejos y la capacidad de adhesión a las superficies como tienen las arañas, es capaz de trepar como nadie inmensas alturas y para ello además se vale de telarañas que creó él mismo a través de su impactante inteligencia.',
      perfil: 'El hombre araña, Parker, un huérfano, vivía con su amable tía May y su tío es un personaje muy querido al rededor del mundo gracias a los poderes que le otorgó una araña radioactiva y a la historia de su vida.'
    },
    {
      nombre: 'Wolverine',
      bio: 'James Howlett nació de los ricos John y Elizabeth Howlett en Alberta, Canadá, durante los últimos años del siglo XIX. Cuando era niño, era frágil e insalubre debido a su sistema inmunitario mutante hiperactivo y fue descuidado por su madre, quien había sido institucionalizada tras la muerte de su primer hijo, John Jr., en 1897. Las habilidades mutantes de James se activaron cuando su padre fue baleado por el jardinero de Howlett, Thomas Logan, quien no sabía que era su verdadero padre. James mató a Logan, cortó la cara del hijo de Logan y su amigo Dog, y se fue de Alberta con una amiga de la infancia, Rose O’Hara. Sus habilidades de curación sacaron el trauma de sus recuerdos, dejándolo parcialmente amnésico. Él y Rose encontraron refugio en una cantera de piedra de la Columbia Británica, donde Rose, alegando que James era su primo, dio su nombre como “Logan”. En unos meses, los poderes de Logan aumentaron debido al ambiente que lo rodeaba. Se volvió más saludable y adquirió sentidos para rivalizar con los de un animal, pero también se volvió más violento. Para desviar parte de esta rabia contenida, Logan participó en peleas en la jaula donde su destreza le valió el apodo de “Wolverine”.  Después de asesinar accidentalmente a Rose con sus garras, Logan se retiró al bosque en donde vivió como una bestia salvaje, perdiendo todos sus recuerdos. Más tarde, volvería a entrar en la sociedad y viajaría por el mundo, participando en todos los conflictos principales del siglo XX (la Primera Guerra Mundial, la Segunda Guerra Mundial, la Guerra Civil Española, la Guerra de Vietnam) como soldado, criminal o mercenario a sueldo. Esto hizo que él acuñara la frase: “Soy lo mejor que hay en lo que hago, pero lo que mejor hago no es muy bueno”. Mientras escapaba de la ley, fue secuestrado por el programa canadiense de súper soldado conocido como “Weapon X”. Anteriormente había participado activamente en el programa a principios de la década de 1960 como agente internacional del Equipo X. Logan era un candidato principal para esta nueva versión de Weapon X debido a su increíblemente rápida curación y resistencia, lo que le permitió al Doctor Cornelius y su equipo fusionar adamantium a su esqueleto. El experimento fue exitoso y le dio a Logan más control sobre su naturaleza berserker, pero también le borró de cualquier recuerdo residual que tuviera en su cabeza. Cuando Hulk se abrió camino en territorio canadiense, Logan se movilizó para luchar contra él. También lo usaron para matar a toda la población de una pequeña ciudad en una prueba de campo, pero finalmente se liberó de sus captores y mató a casi todos en la instalación de Weapon X. A pesar de esto, todavía tenían su ADN y fueron capaces de crear nuevos mutantes como Avery Connor y un clon de garras llamado X-23 (también conocida como Laura Kinney). Su verdadero sentido de pertenencia no llegaría hasta que se uniera a los X-Men.',
      img: 'assets/img/wolverineperfil1.jpg',
      aparicion: '1974-11-01',
      casa: 'Marvel',
      poder: 'Los rápidos poderes de regeneración de Wolverine le permiten recuperarse de casi todos los tipos de heridas corporales mientras que su cabeza permaneciera firmemente sujeta a sus hombros. Sin embargo, el tiempo de cada curación es comprensiblemente proporcional a la gravedad de la lesión. Su cuerpo también es inmune a la mayoría de los venenos, medicamentos y enfermedades; Su agilidad, reflejos y sentidos son igualmente mejorados. Wolverine ve y escucha cosas a distancias mucho mayores que las de los humanos comunes. Su sentido del olfato está aún más magnificado y puede reconocer a las personas y los objetos solo por el olor, lo que, combinado con el entrenamiento de combate y sigilo, lo convierte en uno de los rastreadores más importantes del mundo. Las más emblemáticas de sus armas naturales son seis garras de hueso retráctiles, ligeramente curvadas, de un pie de largo, tres en cada brazo, debajo de la piel y el músculo de sus antebrazos. Él puede, a voluntad, liberar estas garras a través de la piel debajo de sus nudillos. Las garras son naturalmente afiladas y más resistentes que los huesos humanos normales, lo que les permite penetrar en la mayoría de los tipos de carne y materiales naturales.',
      perfil: 'Conocido como Logan, Es un mutante que posee sentidos afinados a los animales, capacidades físicas mejoradas, poderosa capacidad de regeneración conocida como un factor de curación, y tres garras retráctiles en cada mano.'
    },
    {
      nombre:'Superman',
      bio: 'Superman nace en un mundo extraño a una especie tecnológicamente avanzada que se parece a los humanos. Poco después de nacer, su planeta se destruye en un cataclismo natural, pero el padre científico de Superman previó la calamidad y salva a su hijo bebé enviándolo a la Tierra en una pequeña nave espacial. Lamentablemente, la nave es demasiado pequeña para llevar a alguien más, por lo que los padres de Superman se quedan atrás y mueren. Las primeras tiras de periódicos nombran el planeta "Krypton", el bebé "Kal-L" y sus padres biológicos "Jor-L" y "Lora"; sus nombres fueron cambiados a "Jor-el" y "Lara" en una novela de 1942 de George Lowther. La nave aterriza en el campo estadounidense, donde los Kents, una pareja de agricultores, descubren al bebé. Los Kents nombran al niño Clark y lo crían en una comunidad agrícola. Un episodio de la serie de radio de 1947 ubica a esta comunidad anónima en Iowa. Se llama Smallville en Superboy # 2 (junio de 1949). La película de Superman de 1978 lo colocó en Kansas, como lo han hecho la mayoría de las historias de Superman desde entonces. New Adventures of Superboy# 22 (octubre de 1981) lo colocan en Maryland. Los Kents le enseñan a Clark que debe ocultar sus orígenes de otro mundo y usar sus fantásticos poderes para hacer el bien. Clark crea la identidad disfrazada de Superman para proteger su privacidad personal y la seguridad de sus seres queridos. Como Clark Kent, usa anteojos para disfrazar su cara y usa su traje de Superman debajo de su ropa para que pueda cambiarse en cualquier momento. Para completar este disfraz, Clark evita la confrontación violenta, prefiriendo escabullirse y cambiarse a Superman cuando surge el peligro, y sufre un ridículo ocasional por su aparente cobardía.',
      img:'assets/img/supermanperfil.png',
      aparicion:'Junio de 1938',
      casa:'DC',
      poder:'Entre sus poderes se cuenta la súper fuerza, invulnerabilidad, la capacidad de volar, visión calorífica, el aliento helado... Habilidades sin parangón que, sin embargo, no son las únicas del Hombre de Acero. ',
      perfil:'Kal-El llegó a la Tierra desde el planeta Krypton y fue encontrado por una pareja de granjeros que lo nombró Clark Kent y lo crió como propio. Descubriendo sus enormes poderes, lo inspiraron a convertirse en un héroe.'
    },
    {
      nombre:'La Mujer Maravilla',
      bio: 'En su tierra natal es conocida como la princesa Diana de Temiscira pero fuera de esta utiliza la identidad secreta de Diana Prince. Tomó su nombre de la diosa de la caza. Fue formada en un principio por su madre en una figura de arcilla. Se le concedió vida por la súplica de su madre (Hipólita) a la diosa Afrodita. Concebida de este modo por gracia de una diosa, Diana creció siendo la más bella amazona de la Isla Paraíso, con la sabiduría de Atenea, tan fuerte como Hércules y más ágil y veloz que Hermes. Contrariando los deseos de su madre, con un disfraz logró escabullirse y ganar la competición para elegir la amazona más poderosa, la que debía partir de la Isla para auxiliar a los mortales en su lucha contra el nazismo. Con posterioridad, y como consecuencia de la saga Crisis en Tierras Infinitas (Crisis on Infinite Earths), su origen fue revisado por George Pérez. Otros autores que han realizado grandes aportes a la historia de Wonder Woman son: Mike Deodato Jr, en la saga titulada "El torneo"; Phil Jiménez, quien con la historia "La bruja y la guerrera" narró una saga épica donde Diana reúne a un ejército de heroínas para luchar contra la hechicera Circe; y, más recientemente, Greg Rucka en una controvertida etapa que dividió a los fans del personaje, y Gail Simone, que para muchos significa el resurgir de la princesa amazona, sumida en los últimos tiempos en una calidad mediocre, pero que también divide a los fans respecto de su calidad.',
      img:'assets/img/mujermaravillaperfil.png',
      aparicion:'Diciembre de 1941',
      casa:'DC',
      poder:'Posee una gran fuerza que fácil rivaliza la de los Kriptonianos más poderosos (Superman, Supergirl) y posee una increíble inteligencia, pues ella tiene conocimiento de magia, ciencias, sabe más de 10 idiomas y es considerada una de los miembros más sabios e inteligentes de la Liga de la Justicia. Puede volar a grandes velocidades. Es vulnerable pero es considerada a un nivel de diosa por el resto de los superhéroes ya que no envejece, es inmortal, y posee una belleza extraordinaria. Junto a esto, se trata de una excepcional combatiente cuerpo a cuerpo con o sin armas, entrenada en formas de combate utilizadas por las amazonas y tiene conocimiento de artes marciales orientales, entrena diariamente con miembros de la Liga como Batman o Black Canary, llegando incluso a superarlos en combate mano a mano. En varias ocasiones, se le ha visto entrenando con I-Ching, un excelente artista marcial, antiguo maestro de Bruce Wayne. Además de ser la embajadora de las amazonas hacia el resto del mundo, Wonder Woman posee estupendas habilidades y dones superhumanos, concedidos a ella por los dioses griegos en su victoria. Entre ellos se incluyen un lazo mágico que obliga a decir la verdad, hace perder la memoria y es indestructible. Su tiara, que sirve como boomerang y unos brazaletes reflectantes de una aleación de materiales, entre ellos un metal oriundo de la Isla Paraíso llamado "feminum" (en la edad de oro) a prueba de todo tipo de rayos, balas y otros proyectiles, "amazonium" (edad de plata), muy similar al anterior, y fragmentos del escudo de Zeus, la Aegis (post crisis). Ella siempre prefiere fomentar la paz en lugar de la guerra y utilizar su persuasión en lugar de su superfuerza para someter a los malhechores. Wonder Woman tiene dos debilidades en la etapa post crisis: pierde sus poderes cuando es atada con su propio lazo mágico, y también si un hombre une sus brazaletes de modo que la dejan inmovilizada como si se tratara de unas esposas.',
      perfil:'Del universo de superhéroes de los cómics, la Mujer Maravilla es sin dudas la representante femenina más popular y famosa del planeta. Dispone de superpoderes que la destacan y la hacen invencible en su lucha contra el mal, porque ese es su propósito.'
    },
    {
      nombre:'Pantera Negra',
      bio: 'Pantera Negra es el título ceremonial otorgado al jefe de la tribu Pantera de la avanzada nación africana de Wakanda. Además de gobernar el país, también es el jefe de sus diversas tribus (colectivamente denominadas Wakandas). El traje de Pantera es un símbolo de la oficina (jefe de estado) y se utiliza incluso durante misiones diplomáticas. En un pasado distante, un meteorito hecho de vibranium (ficticio), que absorbe la vibración, se estrelló en Wakanda y fue desenterrado. Razonando que los extranjeros explotarían a Wakanda por este valioso recurso, el gobernante, el rey T Chaka, al igual que su padre y otras panteras antes que él, ocultó su país del mundo exterior. La primera esposa de TChaka, NYami, murió mientras estaba de parto con TChalla, y su segunda esposa, Ramonda, fue hecha prisionera por Anton Pretorius durante una visita a su tierra natal de Sudáfrica, por lo que durante la mayor parte de su infancia TChalla fue criado solo por su padre. TChaka fue asesinado por el aventurero Ulysses Klaw en un intento de apoderarse del montículo de vibranium. Con su gente todavía en peligro, un joven T Challa usó el arma sonora de Klaw contra Klaw y sus hombres, destrozando la mano derecha de Klaw y obligándolo a huir. T Challa era el siguiente en la línea para ser el rey de Wakanda y Pantera Negra, pero hasta que estuvo listo para convertirse en el líder de la nación, su tío S yan (el hermano menor de T Chaka) pasó con éxito las pruebas para convertirse en la Pantera Negra. Mientras estaba en su rito de paso en Wakanda, T Challa conoció y se enamoró de la aparentemente huérfana adolescente Ororo Munroe, quien creció hasta convertirse en el miembro de los X-Men, Tormenta.3Los dos rompieron su relación debido a su deseo de vengar la muerte de su padre y convertirse en el hombre que podría liderar adecuadamente a Wakanda, pero se verían a lo largo de los años cuando pudieran.',
      img:'assets/img/Black_Pantherperfil.png',
      aparicion:'The Fantastic Four N.º 52 (1966)',
      casa:'Marvel',
      poder:'El título de "Pantera Negra" es un rango de cargo, jefe del Clan de la Pantera de Wakanda. Como jefe, la Pantera tiene derecho a comer una hierba especial en forma de corazón que le otorga sentidos sobrehumanos agudos, fuerza mejorada, velocidad, agilidad, resistencia, durabilidad, curación y reflejos.',
      perfil:'Es el primer superhéroe de tez negra de la historia de Marvel y se debe destacar que el personaje fue creado con anterioridad al Partido Pantera Negra, el cual fue fundado en octubre del mismo año. Es el rey y protector de la ficticia nación africana de Wakanda'
    },
    {
      nombre:'la Viuda Negra',
      bio: 'Nació en Rusia en 1928, diez años más tarde que el Capitán América. En la Segunda Guerra Mundial, en su ciudad Stalingrado perdió a sus padres en una explosión e incendio causados por una bomba. Ivan Petrovich Bezukhov que servía en el servicio militar como soldado, la adoptó, supo ver y explotar las habilidades que iba adoptando Natasha, otorgándole entrenamiento desde sus primeros años. La organización criminal La Mano (conocida por los cómics de Daredevil) la capturó, mejorando sus habilidades de lucha en estos años. Tras ser rescatada de nuevo por su mentor Ivan, para servir a sus país se introdujo junto a 28 huérfanas en el Programa Viuda Negra, un proyecto secreto de la inteligencia secreta soviética cuyo objetivo era formar soldados con grandes habilidades, tenaces y eficaces espías a utilizar por la KGB. La sede se hacia llamar la Sala Roja. Allí se les lavó el cerebro y se les mejoró biotecnológicamente.',
      img:'assets/img/viudanegraperfil.png',
      aparicion:'Abril de 1964',
      casa:'Marvel',
      poder:'La Viuda Negra es un atleta de clase mundial, gimnasta, acróbata, aerista, capaz de realizar numerosas maniobras y hazañas complejas, experto artista marcial (incluyendo Jiu-jitsu, Aikidō, Boxeo, Judo,  Karate, Savate, Ninjutsu, varios estilos de Kung Fu y Kenpo, así como el arte marcial ruso Sambo), tiradora y especialista en armas, además de tener un extenso entrenamiento de espionaje',
      perfil:'Natasha Romanoff es el nombre real de Viuda Negra fué adoptada por Ivan Petrovich Bezukhov que servía en el servicio militar como soldado, supo ver y explotar las habilidades que iba adoptando Natasha, otorgándole entrenamiento.'
    },
    {
      nombre:'Capitan America',
      bio: 'El capitán América tiene su origen en la primera guerra mundial el cap ingreso a la academia militar porque deseaba ser soldado pero un problema era asmático y era muy delgado y tenia problemas para adaptarse a la academia pero su mejor amigo bucky barnes (el soldado del invierno) lo apoyo en todo momento el por su físico no se podía graduar pasaron meses y no podía. En ese tiempo howard stark hizo un suero que podria convertir a un delgado sin fuerza como steve en un súper humano, como no había voluntarios steve se ofreció para el suero y se hizo súper fuerte, veloz y mas resistente a golpes .',
      img:'assets/img/capitanamericaperfil.jpg',
      aparicion:'Marzo de 1941',
      casa:'Marvel',
      poder:'La experiencia de batalla y el entrenamiento de Rogers lo convierten en un experto táctico y un excelente comandante de campo, ya que sus compañeros de equipo con frecuencia respetan sus órdenes en la batalla. Thor ha declarado que Rogers es uno de los pocos humanos de los que recibirá órdenes y seguirá "a través de las puertas de Hades". Los reflejos y sentidos de Rogers son extraordinariamente agudos. Ha mezclado Aikido, Boxeo, Judo, Karate, Jujutsu, Kickboxing, y la gimnasia en su propio estilo de lucha único y es un maestro de las artes marciales múltiples. Años de práctica con su escudo casi indestructible le permiten apuntar y lanzarlo con una precisión casi infalible. Su habilidad con su escudo es tal que puede atacar a múltiples objetivos en sucesión con un solo lanzamiento o incluso provocar un bumerán, como un retorno de un lanzamiento para atacar a un enemigo desde atrás. En cambio, otros combatientes expertos lo consideran como uno de los mejores combatientes cuerpo a cuerpo en el Universo Marvel, limitado solo por su físico humano.Aunque el suero del supersoldado es una parte importante de su fuerza, Rogers se ha mostrado todavía suficientemente capaz contra oponentes más fuertes, incluso cuando el suero ha sido desactivado volviéndolo a su físico anterior al Capitán América. ',
      perfil:'El capitán América en los cómic no es un miembro fundador pero si uno importante ya que ha liderado numerosas guerras con the avengers sin embargo puede que sin los vengadores el no estuviera en esta época'
    },
  ];
  constructor() { }

  getHeroes(): Heroe[]{
    return this.heroes;
  }

  getHeroeDetalleId(id: number){
    return this.heroes[id];
  }

  buscadorHeroe(termino: string){
    let heroeItem: Heroe[] = [];
    termino = termino.toLowerCase();
    for (const heroe of this.heroes){
      const nombre = heroe.nombre.toLowerCase();
      if (nombre.indexOf(termino) >= 0 ){
        heroeItem.push(heroe);
      }
    }
    return heroeItem;
  }
}

export interface Heroe{
  nombre: string;
  bio: string;
  img: string;
  aparicion: string;
  casa: string;
  poder: string;
  perfil: string;
}
